### ISSUE TITLE
States solved in 4.2.0?

### ISSUE THREAD

**Issue by trendol** [emilohman/homey-plejd#1]
4.2.0 came with a BTE ”allow write with response”. Could that solve the issue with knowing the lights states directly in Homey?

**Comment by emilohman** [comment]
Sorry for very very late response!
No I'm afraid not. But Athom has told that they will fix it in Q2 this year. 
In the meantime I'm about to release à version that uses polling to check for device state.

**Comment by emilohman** [comment]
Now is the version using polling to get state live: https://homey.app/sv-se/app/se.emilohman.plejd/Plejd/
