### ISSUE TITLE
Homey 6.1 trasig app

### ISSUE THREAD

**Issue by jampeef** [emilohman/homey-plejd#12]
Får capability listener onoff error på lina plejd ctrs
Med senaste versionen. Funkade för några versioner sedan.

**Comment by emilohman** [comment]
Får du fortfarande det problemet? Har du provat att starta om appen eller Homey?
Har inte fått in några felrapporter om det tidigare men har sätt att vissa får sånna fel i andra appar så det kan vara en generellt problem i Homey.

**Comment by jampeef** [comment]
Tog bort dem och la in dem igen då fungerade flows men inte manuellt. Men sedan nu v7 rc8 fungerar dem perfekt igen. Måste vara nån homey bugg och inget med plejd appen 😁

**Comment by emilohman** [comment]
Skönt att det funkar igen!
