### ISSUE TITLE
V7.0 rc14 så fungerar det inte igen

### ISSUE THREAD

**Issue by jampeef** [emilohman/homey-plejd#13]
Dem var tillbaka och fungerade förra homey versionen nu är dem utslagna igen. Jag har märkt att dem fungerar ibland, men med mellan 30 sek och 5 min fördröjning

**Comment by emilohman** [comment]
Ok synd. Har du provat att starta om Homey efter du fått in ny version av Homey firmware?

**Comment by jampeef** [comment]
Jepp jag har startat om. Ska prova testa lite mer men det känns svårt att
felsöka.

**Comment by emilohman** [comment]
Du får gärna skicka din logg genom att gå till Mer->Appar->Plejd->Kugghjul->Skapa diagnostikrapport.

**Comment by jampeef** [comment]
ab739f6a-7475-44d8-8eed-0a5be533caf5

**Comment by pkdev** [comment]
Samme problem her v 7.1.1
f7e2c89d-6b9e-4777-a6fb-77a99f55cfb9

**Comment by olssonjoakim** [comment]
@emilohman Vet du om det är någon / du som har fått igång det igen? 
Jag har nyligen installerat en ny Homey med en uppsättning Plejd prylar och hade hoppats att kunna köra det ihop. Men ack så snopet när det inte funkade... :(

**Comment by jampeef** [comment]
Är ju nån bugg med homey. Det laggar magiskt mycket så mycket att det
oftast blir timeout. Sen ibland så fungerar det hur bra som helst några
gånger.

**Comment by olssonjoakim** [comment]
Jag startade om Homey, drog ner det här projektet och körde i utvecklingsläge. Enheterna hittades och sen bytte jag till den publicerade versionen av applikationen och nu funkar det ;)

**Comment by jampeef** [comment]
Har testat det också. Fungerar några gånger sen är det tillbaka till
laggen.

**Comment by emilohman** [comment]
Hej!
Det ni skulle kunna prova är att flytta Homeyn så den får bättre signal mot Plejd. Räckvidden är ganska dålig för BLE och speciellt om det är många väggar och sånt i vägen samt att wifi och andra bluetooth prylar kan störa signalen.
Om ni går till den här sidan: https://tools.developer.homey.app/tools/ble så kan ni se RSSI som är signalstyrkan från Homey till BLE enheter runt om. Det som är intressant i det här fallet är de som heter P mesh. 
Personligen har jag rssi runt-80 vilket är ganska dåligt men det fungerar hur bra som helst.. 
I vissa fall kan det bli bättre med att byta kanal på wifi (https://support.zwift.com/en_us/ble-vs-ant-interference-troubleshooting-tips-ryUhOTnzH)..

**Comment by jampeef** [comment]
Tjena.


Ska testa nu har bytt kanaler på wifin. Hade lämnat kanal 1 ledig tidigare.
Kör med kanal 11 ledigt nu så får se hur det går. Återkommer med resultat

**Comment by jampeef** [comment]
Verkar ha för dålig täckning på BLE . Ligger på -83 DB på den som är
närmast. Har bara 3st. Man kanske skulle kunna lägga till en puck som är
närmare för att få bättre täckning möjligtvis

**Comment by mojento** [comment]
Hallå! 

Det här kanske är en dum fråga, men när jag tittar på BLE så får jag upp "P Mesh" löpnummer på 12 siffror och Connected by SE.EMILOHMAN.PLEJD när jag klickar där så får jag upp lite mera info och ser bl.a. RSSI -76

Jag räknar till 17 stycken enheter via plejd men ser bara 9 stycken i Homey.

Om jag klickar på "Discover Devices" så dyker dyker 12! stycken enheter upp, utöver den som heter SE.EMILOHMAN.PLEJD

Hur ska jag tolka det? deras RSSI-värden varierar mellan 63 och 99... 

Har en plejd ca 1 meter ifrån Homey och sen är det nog inte mer än max 5-6 meter som längst mellan dem.

**Comment by emilohman** [comment]
Homey söker i 5s efter ble enheter och sparar dom i 30s och sen kan man söka i 5s igen osv. Under dom 5s lyckas Homey hitta 9st. Kan bli fler eller färre vid nästa sökning beroende på hur ofta Plejd skickar sin signal. I Homey version 5 och lägre kunde man söka i 30s efter ble enheter och kunde då hitta fler och det verkade fungera bättre för fler då.

I min app försöker jag ansluta till den med bäst rssi, om det inte går provar jag nästa tills alla är provade då börjar den om igen..

**Comment by mojento** [comment]
Det låter som om felet ligger i Homey, såg att det fanns en öppen ticket hos dem... men vet inte hur hög prio det har.

Finns det något vi kan göra?

**Comment by emilohman** [comment]
Nej jag vet inte.. inte mer än att testa att få bättre mottagning med Bluetooth. Annars kan vi hjälpas åt att få Homey att prioritera: https://github.com/athombv/homey-apps-sdk-issues/issues/203 

Sen för Plejds skulle räcker det med att Homey får kontakt med en Plejd puck.. sen meshas signalen mellan alla puckarna.

**Comment by emilohman** [comment]
Homey v7.2.1 innehåller fixar för BLE anslutningen. Vore intressant och veta om det fungerar bättre nu? 
Plejd appen har börjat fungera igen för vissa..

**Comment by jampeef** [comment]
Kanske om man tar bort allt och lägger till igen. Ska prova. Nu när jag
uppdaterat så har jag fortfarande röda utropstecken på alla plejd, så jag
kan inte trycka på dem men dem fungerar med lagg i flows oftast

Den fre 17 dec. 2021 18:53Emil Öhman ***@***.***> skrev:

**Comment by jampeef** [comment]
💪 nu är allt som vanligt igen. Avinstallerad appen från homey och
återinstallerade igen. Nu fungerar dem perfekt ,nästa bättre än i plejd
appen

Den tors 10 juni 2021 21:17Emil Öhman ***@***.***> skrev:

**Comment by emilohman** [comment]
Skönt att höra!
