### ISSUE TITLE
Don't  work 7.2.0

### ISSUE THREAD

**Issue by haakaak** [emilohman/homey-plejd#17]
Hi.  Is quite new Homey University.  Has recently installed / connected to several devices by Plejd.  Have also connected / added these to Homey, but they do not work. Hope there any solution on this??  Do not know if this worked before 7.2.0.

**Comment by emilohman** [comment]
It's supposed to work, it works for me and others.Have you tried to restart your Homey? What's your distance between Homey and the closest Plejd device?

**Comment by haakaak** [comment]
Hi Emil
Thanks for reply
It looks like it works now. I do not know exactly what I have done. It did not work when I restarted Homey, and the distance to the nearest Plejd has 4-5 meters 3 pcs. But I installed 2 more Plejd yesterday. So this may be what has made the difference.

**Comment by emilohman** [comment]
Ok.. but great that it works now 😀

**Comment by haakaak** [comment]
Takk for hjelpen



fre. 17. des. 2021 kl. 18:50 skrev Emil Öhman ***@***.***>:
