### ISSUE TITLE
Plejd doesn't work with 7.3.0 version of Homey 

### ISSUE THREAD

**Issue by PetOlaus** [emilohman/homey-plejd#25]
Homey updated automaticly and after that the plejd Bluetooth mesh is not working.

**Comment by emilohman** [comment]
Sorry to hear that! Have you tried restarting your Homey? If that not’s helping please send me an ettor report from: More->Apps->Plejd->Gear wheel->Send diagnosticreport. 
And also send an error report to Homey from: More->Settings->Generall->Create diagnosticreport. And post the Id here so I can send it to Homey.

**Comment by PetOlaus** [comment]
The restart of the Homey solved my problem.... how easy it is sometimes. Thanks for a quick and helpful reply 😄👍
