### ISSUE TITLE
Problem with 2.0.2

### ISSUE THREAD

**Issue by pahen** [emilohman/homey-plejd#4]
I can longer control my Plejd devices. And the ”configure app” is no longer visible in the  app.

**Comment by emilohman** [comment]
Unfortunately there is a problem with version 2.0.2 that causes the app to crash. A fix is waiting to be approved by Athom but it is available as experimental here: https://homey.app/sv-se/app/se.emilohman.plejd/Plejd/test/

**Comment by pahen** [comment]
Perfect, test version works 👍
