### ISSUE TITLE
On/off status wrong if dimmer slider used.

### ISSUE THREAD

**Issue by gorper** [emilohman/homey-plejd#50]
Greetings. I just noticed a kind of small issue on a dim-01 device if I in homey iOS app or web app choose to adjust dim level to turn on the lamp. The status and on/off switch do not update to on but the lamp turns on at the dim level set. I see when I test some more devices I have some of them act like this others correct, so turning on the lamp by adjust dim level activates on/off button and show correct status. Sorry to miss I am running latest app on a homey early 2019pro

**Comment by emilohman** [comment]
Should be fixed in version 3.3.6, released today. Please try it out.
