### ISSUE TITLE
Plejd relä ctr-01 funkar inte med Early 2018 

### ISSUE THREAD

**Issue by Mefiboset666** [emilohman/homey-plejd#56]
Hej. Jag kan inte styra min plejdpuck men jag ser enheten och den blir gul och vit men inget händer. Jag kan styra den via min plejdapp.  Jag har ingen gateway men det skulle ju funka utan. Har no nåt tips ? Är ganska ny på detta.

**Comment by emilohman** [comment]
Hur många enheter har du? Har du bara en enhet kan inte Homey koppla upp om du samtidigt använde telefonen. Har du fler enheter skall det fungera.
Har du din Homey tillräckligt nära Plejd puckarna? Ganska dålig räckvidd på bluetooth?

**Comment by Mefiboset666** [comment]
Det funkar nu när jag satt den närmare. Har funkat hela tiden sen dess

ons 22 nov. 2023 kl. 12:48 skrev Emil Öhman ***@***.***>:

**Comment by emilohman** [comment]
Skönt att det löste sig!
